### ISSUE TITLE
Invoice line with 100% discount will become 6 characters due to scale set to 2, but the REST API only accepts 5

### ISSUE THREAD

**Issue by paulrene** [SendRegning/sws-client-java#1]
Line 50 of InvoiceLineHelper (https://github.com/SendRegning/sws-client-java/blob/master/src/main/java/no/sws/invoice/line/InvoiceLineHelper.java#L50):

    result.add(new Element("discount").setText(discount.setScale(2, BigDecimal.ROUND_HALF_UP).toPlainString()));

For discount values of 100 this will produce a String that is 6 characters long ("100.00"), but the RESP API only supports 5 characters for this field, ref. your documentation at https://github.com/SendRegning/sws-client-java/blob/master/docs/send-invoice.md that states the following data type definition for the discount field:

> Decimal - maximum 5 characters, including punctuation marks. Must be >= 0 or >= 100

Attempting to send an invoice with a 100% discounted invoice line will yield the following HTTP error:

> HTTP Status 400 - discount element value in line element number 4 in invoice element number 1 can't contain more than 5 characters

The use case where we discovered this issue are:

We are invoicing team activity memberships for kids in a sports club. We have a rule where the kids only pay for the first 2 activities. When a kid participate in 3 teams we invoice all the memberships, but give a 100% discount to show the parents that the membership has been registered.

I was tempted to change the change the scale to 1 to circumvent this bug and send a pull request. I chose not to do this since this would limit the amount of scale you are allowed to use in the Java API and could break other client implementations. I believe this has to be fixed on the server side of the API.

**Comment by orby** [comment]
Nice finding, Paul Rene :-)

Since SWS is "deprecated", we will not touch the backend for this issue. I made a fairly quick and dirty fix in the client so now it sends "100" instead of "100.00" when line discount is equal to 100% (which is ok).

**Comment by orby** [comment]
Just to clarify what we mean when we say that SWS is "deprecated".

SWS was designed and implemented in 2006/2007 when we had a big monolithic application (with frontend and backend tangled together), so SWS was introduced as a parallel service next to SendRegning browser version.

These days our frontend is just a consumer of our backend API which can serve both integrations and desktop/mobile clients with all features.

We are not sure when we release the documentation for the API, but we are working on it every day :-)
